name: declarative_refresh_indicator
description: A declarative refresh indicator alternative that takes inspiration from the Switch and Checkbox APIs.
version: 0.1.0
homepage: 'https://github.com/hacker1024/declarative_refresh_indicator.dart'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^1.5.3

flutter:
